### ISSUE TITLE
Support for all parts

### ISSUE THREAD

**Issue by Monniasza** [Biotronic/TweakScale#38]
Please add ability to scale all parts using only supported modules.
Ability to use TweakScale with all parts will make most scaling definitions obsolete.

**Comment by Biotronic** [comment]
Hi! I haven't been actively maintaining TweakScale for a few years - you should head over to [Pellinor](https://github.com/pellinor0/TweakScale/issues)'s and file your issue there. :)

**Comment by Monniasza** [comment]
Moved to https://github.com/pellinor0/TweakScale/issues/84
